language: cpp

compiler:
  - clang
  - gcc

script:
  make all
  # todo: build tests and run it
  # todo: build with emcc

after_success:
  # todo: push emcc result to webhost

notifications:
  email:
    - miller.michael@gmx.de
  on_start: false