sudo: required
# Ubuntu 14.04 Trusty support
# dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    #- compiler: clang
      #addons:
       # apt:
        #  sources:
         #   - ubuntu-toolchain-r-test
          #  - llvm-toolchain-precise-3.6
          #packages:
            #- clang-3.6
      #env: COMPILER=clang++-3.6
    #- compiler: clang
      #addons:
        #apt:
          #sources:
            #- ubuntu-toolchain-r-test
            #- llvm-toolchain-precise-3.7
          #packages:
            #- clang-3.7
      #env: COMPILER=clang++-3.7

before_install:
  - git config --global user.name "michael miller"
  - git config --global user.email "MichaelMiller-@users.noreply.github.com"
  - git config --global push.default simple
  - sudo apt-get update -qq
  - sudo apt-get install -y premake4
  - sudo apt-get install -y libsdl2-dev
  - sudo apt-get install -y emscripten

install:
  - export CXX="${COMPILER}"

script:
  - if [ "${CXX}" != "" ]; then (travis_wait make all); fi

  #- if [ "${CXX}" != "" ] && [ "${COVERAGE}" == "" ]; then (travis_wait make test example); fi
  #- if [ "${CXX}" != "" ] && [ "${COVERAGE}" != "" ]; then (travis_wait make test); fi

  #- if [ "${TRAVIS_BRANCH}" == "master" ]; then (git clone https://github.com/boost-experimental/sml && cd sml && rm -rf *); fi

  # todo: build tests and run it
  # todo: build with emcc

after_success:
  # todo: push emcc result to webhost

notifications:
  email:
    - miller.michael@gmx.de
  on_start: false