sudo: false

language: cpp

matrix:
  include:
  - os: linux
    env: CXX=g++-6 CC=gcc-6
    addons:
      apt:
        packages: ["g++-6", "libstdc++-6-dev", "gdb"]
        sources: ["ubuntu-toolchain-r-test"]
  - os: linux
    env: CXX=clang++-3.9 CC=clang-3.9
    addons:
      apt:
        packages: ["clang-3.9", "libstdc++-5-dev", "gdb"]
        sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise"]

script:
  - if [ "${CXX}" != "" ]; then (travis_wait make all); fi
  # todo: build tests and run it
  # todo: build with emcc

after_success:
  # todo: push emcc result to webhost

notifications:
  email:
    - miller.michael@gmx.de
  on_start: false