# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y emscripten

install:
  - export CXX="${COMPILER}"

script:
  - if [ "${CXX}" != "" ]; then (travis_wait make all); fi
  # todo: build tests and run it
  # todo: build with emcc

after_success:
  # todo: push emcc result to webhost

notifications:
  email:
    - miller.michael@gmx.de
  on_start: false