name: Web Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install emsdk
      shell: bash
      working-directory: ${{runner.workspace}}
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        emcc -v
        echo "$EMSDK/upstream/emscripten" >> $GITHUB_PATH
        echo "$EMSDK/upstream/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      shell: bash
      working-directory: ${{runner.workspace}}
      run: |
        git clone https://github.com/Microsoft/vcpkg.git 
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg install spdlog:wasm32-emscripten
        ./vcpkg install nlohmann-json:wasm32-emscripten

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${{runner.workspace}}/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_TOOLCHAIN_FILE=${{runner.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DPLATFORM=Web -DVCPKG_TARGET_TRIPLET=wasm32-emscripten -DBUILD_TESTING=OFF

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config Release

    - name: Sync
      working-directory: ${{runner.workspace}}/build
      run: |
        ls -al *
        echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
        chmod 400 ~/deploy_key
        echo "put bin/orpg.html" > ~/upload_commands
        echo "put bin/orpg.js" > ~/upload_commands
        echo "put bin/orpg.wasm" > ~/upload_commands
        echo "quit" > ~/upload_commands
        sshpass -p 'cat ~/deploy_key' sftp -v web187_orpg@server34.configcenter.info -b ~/upload_commands


